/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIew;
import Controller.CPenerbit;
import Koneksi.KoneksiDB;
import Model.MPenerbit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author microsoft
 */
public class VPenerbitTabel extends javax.swing.JFrame {
KoneksiDB koneksi = new KoneksiDB();
    MPenerbit mb = new MPenerbit();
    CPenerbit cb = new CPenerbit();
    
    PreparedStatement pst  = null;
    Connection conn = null;
    ResultSet rs = null;
    /**
     * Creates new form VPenerbitTabel
     */
    public VPenerbitTabel() {
        initComponents();
        dataTable();
    }
    
    private void bersih()
     {
        
        jTX_KODEPENERBIT.setText("");
        jTX_NAMAPENERBIT.setText("");
        jTX_ALAMAT.setText("");
        jTX_KOTA.setText("");
        jTX_TELEPON.setText("");
      
     }
    
    private void kliktable(){
       try {
            int baris = jTB_JENIS.getSelectedRow();
            jTX_KODEPENERBIT.setText(jTB_JENIS.getValueAt(baris, 0).toString());
            jTX_NAMAPENERBIT.setText(jTB_JENIS.getValueAt(baris, 1).toString());
            jTX_ALAMAT.setText(jTB_JENIS.getValueAt(baris, 2).toString());
            jTX_KOTA.setText(jTB_JENIS.getValueAt(baris, 3).toString());
            jTX_TELEPON.setText(jTB_JENIS.getValueAt(baris, 4).toString());
            
       } catch (Exception e) {
       }
   }
    
    private void dataTable() {
        koneksi.koneksiDatabase();

        DefaultTableModel tabel = new DefaultTableModel();
        
    
        tabel.addColumn("Kode Penerbit");
        tabel.addColumn("Nama Penerbit");
        tabel.addColumn("Alamat Penerbit");
        tabel.addColumn("Kota ");
        tabel.addColumn("Telepon");
       

        jTB_JENIS.setModel(tabel);
        try {
            String sql = "select * from tbl_penerbit";

            ResultSet res = koneksi.state.executeQuery(sql);
            while (res.next()) {
                tabel.addRow(new Object[]{
                    
                    res.getString("kodepenerbit"),
                    res.getString("namapenerbit"),
                    res.getString("alamat"),
                    res.getString("kota"),  
                    res.getString("nope"),
                });
                jTB_JENIS.setModel(tabel);

            }
        } catch (SQLException eer) {
            System.err.println("SQLException:" + eer.getMessage());
        }
    }
    
    private void ubah(){
         try {
            //int id  = Integer.parseInt(jTX_ID.getText());
            String kodepenebit = jTX_KODEPENERBIT.getText();
            String namapenerbit = jTX_NAMAPENERBIT.getText(); 
            String alamat = jTX_ALAMAT.getText();
            String kota = jTX_KOTA.getText(); 
            String nope= jTX_TELEPON.getText(); 

            //mt.setId(id);
            mb.setKodepenerbit(kodepenebit);
            mb.setNamapenerbit(namapenerbit);
            mb.setAlamat(alamat);
            mb.setKota(kota);
            mb.setNope(nope);
  
            cb.ubahData(mb);

            dataTable();

            
        } catch (Exception e) {
            System.err.println("" + e);
        }
   }
    
    public void hapus(){
       try {
            String kodepenerbit= jTX_KODEPENERBIT.getText();
            
            mb.setKodepenerbit(kodepenerbit);//mt didapat dari pembuatan objek, dari kelas ModelTeman (instansiasi dilakukan diatas)
            
            cb.hapusData(mb);//ct didapat dari pembuatan objek, dari kelas ControllerTeman (instansiasi dilakukan diatas)
            
            dataTable();
            
        } catch (NullPointerException e) {
            
        }
      }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBTN_EDIT = new javax.swing.JButton();
        jBTN_DELETE = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTB_JENIS = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTX_KODEPENERBIT = new javax.swing.JTextField();
        jTX_NAMAPENERBIT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTX_ALAMAT = new javax.swing.JTextField();
        jTX_KOTA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTX_TELEPON = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Daftar Penerbit");

        jBTN_EDIT.setText("EDIT");
        jBTN_EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTN_EDITActionPerformed(evt);
            }
        });

        jBTN_DELETE.setText("DELETE");
        jBTN_DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTN_DELETEActionPerformed(evt);
            }
        });

        jTB_JENIS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTB_JENIS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTB_JENISMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTB_JENIS);

        jLabel1.setText("Kode Penerbit");

        jLabel2.setText("Nama Penerbit");

        jLabel3.setText("Alamat");

        jLabel4.setText("Kota");

        jLabel5.setText("Telepon");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Daftar Penerbit Buku");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTX_KODEPENERBIT, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTX_NAMAPENERBIT, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTX_ALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTX_KOTA, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTX_TELEPON, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(123, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBTN_EDIT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBTN_DELETE, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTX_KODEPENERBIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTX_NAMAPENERBIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTX_ALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTX_KOTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTX_TELEPON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBTN_EDIT)
                        .addGap(18, 18, 18)
                        .addComponent(jBTN_DELETE)
                        .addGap(157, 157, 157))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBTN_EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTN_EDITActionPerformed
        // TODO add your handling code here:
        ubah();
        bersih();
    }//GEN-LAST:event_jBTN_EDITActionPerformed

    private void jBTN_DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTN_DELETEActionPerformed
        // TODO add your handling code here:
        hapus();
        bersih();
    }//GEN-LAST:event_jBTN_DELETEActionPerformed

    private void jTB_JENISMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTB_JENISMouseClicked
        // TODO add your handling code here:
        kliktable();
    }//GEN-LAST:event_jTB_JENISMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPenerbitTabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPenerbitTabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPenerbitTabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPenerbitTabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPenerbitTabel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTN_DELETE;
    private javax.swing.JButton jBTN_EDIT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTB_JENIS;
    private javax.swing.JTextField jTX_ALAMAT;
    private javax.swing.JTextField jTX_KODEPENERBIT;
    private javax.swing.JTextField jTX_KOTA;
    private javax.swing.JTextField jTX_NAMAPENERBIT;
    private javax.swing.JTextField jTX_TELEPON;
    // End of variables declaration//GEN-END:variables
}
